# Some Preliminaries and Imports

In [3]:
import os
import json
import numpy as np
import pandas as pd
from collections import Counter

In [4]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [5]:
%cd ./drive/MyDrive/Provinces/
%pwd
%ls

/content/drive/MyDrive/Provinces
Hamedan/  Ilam/  Kermanshah/  Khoozestan/  Lorestan/  Markazi/

# Some Food Tyoe and Occasion Statistics

In [6]:
provinces = ['Hamedan/', 'Ilam/', 'Kermanshah/', 'Khoozestan/', 'Lorestan/', 'Markazi/']

In [10]:
# Number of foods for each province and Types of meal

for province in provinces:
  dir_address = "./" + province + "Modified/"
  province_recipes_file = os.listdir(dir_address)
  meal_type_list = []
  occasion_list = []
  with open(dir_address + province_recipes_file[0], "r", encoding = "utf-8") as f:
      data = json.load(f)
      print(f"{province[0:len(province)-1]}:\n\n")
      print(f"Number of recipes (Records): {len(data)}\n")
      for item in data:
          meal_type_list.extend(item.get('meal_type', []))  # meal_type is a list
          occasion_list.append(item.get('occasion'))

      count = 0
      for occasion in occasion_list:
          if isinstance(occasion, list):
              occasion_list[count] = occasion[0]
          count += 1

      # print(meal_type_list)
      # print(occasion_list)

      meal_type_counts = Counter(meal_type_list)
      occasion_counts = Counter(occasion_list)

      meal_type_df = pd.DataFrame(meal_type_counts.items(), columns=["Type", "amount"])
      left_aligned_meal_type_df = meal_type_df.style.set_properties(**{'text-align': 'left'})
      print("Types of meal:")
      display(left_aligned_meal_type_df)
      print("\n")

      occasions_df = pd.DataFrame(occasion_counts.items(), columns=["Occasion", "amount"])
      left_aligned_occasions_df = occasions_df.style.set_properties(**{'text-align': 'left'})
      print("Occasions:")
      display(left_aligned_occasions_df)
      print("\n")

      f.close()

Hamedan:


Number of recipes: 31

Types of meal:

Occasions:

Ilam:


Number of recipes: 25

Types of meal:

Occasions:

Kermanshah:


Number of recipes: 33

Types of meal:

Occasions:

Khoozestan:


Number of recipes: 44

Types of meal:

Occasions:

Lorestan:


Number of recipes: 30

Types of meal:

Occasions:

Markazi:


Number of recipes: 36

Types of meal:

Occasions:

# Number of Words in the Dataset

In [29]:
numberOfWordsForAllProvinces = {'Hamedan':'', 'Ilam':'', 'Kermanshah':'', 'Khoozestan':'', 'Lorestan':'', 'Markazi':''}
for province in provinces:
  numberOfWordsForEachProvince = 0
  dir_address = "./" + province + "Modified/"
  province_recipes_file = os.listdir(dir_address)
  with open(dir_address + province_recipes_file[0], "r", encoding = "utf-8") as f:
      data = json.load(f)
      for recipe in data:
          numberOfWordsForEachRecipe = 0
          for item in recipe.items():
              if item[0] == 'title':
                  numberOfWordsForEachRecipe += len(item[1].split()) + 1
              elif item[0] == 'location':
                  numberOfWordsForEachRecipe += 7
              elif item[0] == 'ingredients':
                  numberOfIngredientRecords = len(item[1])
                  keyWords = numberOfIngredientRecords * 3 + 1
                  valueWords = 0
                  for IngredientRecord in item[1]:
                      for element in IngredientRecord.items():
                          if isinstance(element[1], str):
                              number_of_element_string_elements = len(element[1].split())
                              valueWords += number_of_element_string_elements
                  numberOfWordsForEachRecipe += (keyWords + valueWords)
              elif item[0] == 'instructions':
                  numberOFWordsInInstructions = 1
                  numberOfInstructionSentences = len(item[1])
                  for sentence_index in range(numberOfInstructionSentences):
                      numberOFWordsInInstructions += len(item[1][sentence_index].split())
                  numberOfWordsForEachRecipe += numberOFWordsInInstructions
              elif item[0] == 'meal_type':
                  if isinstance(item[1][0], str):
                      numberOfWordsForEachRecipe += len(item[1][0].split()) + 1
              elif item[0] == 'occasion':
                  if isinstance(item[1], str):
                      numberOfWordsForEachRecipe += len(item[1].split()) + 1
              elif item[0] == 'images':
                  numberOfWordsForEachRecipe += 6
                  url = item[1].get("main")
                  if isinstance(url, str):
                      numberOfWordsForEachRecipe += len(url.replace('/',' ').replace('-',' ').replace('_',' ').replace('.',' ').split())
              elif item[0] == 'id' or item[0] == 'annotator':
                  numberOfWordsForEachRecipe += 1
              elif item[0] in ['answer', 'annotation_id', 'created_at', 'updated_at', 'lead_time']:
                  numberOfWordsForEachRecipe += 2

          numberOfWordsForEachProvince += numberOfWordsForEachRecipe
      f.close()

  numberOfWordsForAllProvinces[province[0:len(province)-1]] = numberOfWordsForEachProvince

_sum = 0
for province in numberOfWordsForAllProvinces.items():
    _sum += province[1]

print(f"Number of Words in the whole dataset (including URLs and Keys and Null or None values): {_sum}")

Number of Words in the whole dataset (including URLs and Keys and Null or None values): 49084

# Mean of String Literal Lengths in the Dataset

In [33]:
meanOfSTRLensForAllProvinces = {'Hamedan':'', 'Ilam':'', 'Kermanshah':'', 'Khoozestan':'', 'Lorestan':'', 'Markazi':''}
for province in provinces:
  dir_address = "./" + province + "Modified/"
  province_recipes_file = os.listdir(dir_address)
  with open(dir_address + province_recipes_file[0], "r", encoding = "utf-8") as f:
      data = json.load(f)
      recipeInstructionMeanSentenceLen = 0
      numberOfRecipes = len(data)
      for recipe in data:
          instructionSentenceLenMean = 0
          for item in recipe.items():
              if item[0] == 'instructions':
                  # numberOfInstructionsSentences = len(item[1])
                  Sentences = ''.join(item[1])
                  Sentences = Sentences.split('.')
                  numberOfSentencesInInstruction = len(Sentences)
                  numberOfWordsInThisSentence = np.zeros(numberOfSentencesInInstruction)
                  index = 0
                  for sentence in Sentences:
                      numberOfWordsInThisSentence[index] = len(sentence.split())
                      index += 1
                  sumOfAllWordsOfAllSentencesInThisInstruction = np.sum(numberOfWordsInThisSentence)
                  instructionSentenceLenMean = sumOfAllWordsOfAllSentencesInThisInstruction/numberOfSentencesInInstruction
                  break

          recipeInstructionMeanSentenceLen += instructionSentenceLenMean

      meanOfSTRLensForAllProvinces[province[0:len(province)-1]] = recipeInstructionMeanSentenceLen/numberOfRecipes

  f.close()

numberOfProvinces = len(meanOfSTRLensForAllProvinces)
_sum = 0
for item in meanOfSTRLensForAllProvinces.items():
    _sum += item[1]
MeanOfSentenceLens = _sum/numberOfProvinces

print(f"Mean of Sentence Lengths in all 6 Provinces is: {int(MeanOfSentenceLens)}")

Mean of Sentence Lengths in all 6 Provinces is: 44