# Some Preliminaries

In [1]:
!pip install hazm
!pip install dadmatools

Requirement already satisfied: hazm in /usr/local/lib/python3.11/dist-packages (0.10.0)
Requirement already satisfied: fasttext-wheel<0.10.0,>=0.9.2 in /usr/local/lib/python3.11/dist-packages (from hazm) (0.9.2)
Requirement already satisfied: flashtext<3.0,>=2.7 in /usr/local/lib/python3.11/dist-packages (from hazm) (2.7)
Requirement already satisfied: gensim<5.0.0,>=4.3.1 in /usr/local/lib/python3.11/dist-packages (from hazm) (4.3.3)
Requirement already satisfied: nltk<4.0.0,>=3.8.1 in /usr/local/lib/python3.11/dist-packages (from hazm) (3.9.1)
Requirement already satisfied: numpy==1.24.3 in /usr/local/lib/python3.11/dist-packages (from hazm) (1.24.3)
Requirement already satisfied: python-crfsuite<0.10.0,>=0.9.9 in /usr/local/lib/python3.11/dist-packages (from hazm) (0.9.11)
Requirement already satisfied: scikit-learn<2.0.0,>=1.2.2 in /usr/local/lib/python3.11/dist-packages (from hazm) (1.6.1)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.11/dist-packages (from fasttext-wheel<0.10.0,>=0.9.2->hazm) (2.13.6)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from fasttext-wheel<0.10.0,>=0.9.2->hazm) (75.2.0)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim<5.0.0,>=4.3.1->hazm) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim<5.0.0,>=4.3.1->hazm) (7.1.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (4.67.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2.0.0,>=1.2.2->hazm) (3.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim<5.0.0,>=4.3.1->hazm) (1.17.2)
Collecting dadmatools
  Using cached dadmatools-2.1.8-py3-none-any.whl.metadata (22 kB)
Collecting bpemb==0.3.6 (from dadmatools)
  Using cached bpemb-0.3.6-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: nltk==3.9.1 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (3.9.1)
Collecting folium==0.19.3 (from dadmatools)
  Using cached folium-0.19.3-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting h5py==3.12.1 (from dadmatools)
  Using cached h5py-3.12.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting Deprecated==1.2.6 (from dadmatools)
  Using cached Deprecated-1.2.6-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: hyperopt==0.2.7 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (0.2.7)
Collecting pyconll==3.2.0 (from dadmatools)
  Using cached pyconll-3.2.0-py3-none-any.whl.metadata (8.0 kB)
Collecting segtok>=1.5.7 (from dadmatools)
  Using cached segtok-1.5.11-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: tabulate==0.9.0 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (0.9.0)
Requirement already satisfied: gensim==4.3.3 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (4.3.3)
Collecting conllu==6.0.0 (from dadmatools)
  Using cached conllu-6.0.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: gdown==5.2.0 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (5.2.0)
Collecting py7zr==0.22.0 (from dadmatools)
  Using cached py7zr-0.22.0-py3-none-any.whl.metadata (16 kB)
Collecting html2text==2024.2.26 (from dadmatools)
  Using cached html2text-2024.2.26.tar.gz (56 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-learn==1.6.0 (from dadmatools)
  Using cached scikit_learn-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting numpy==1.26.4 (from dadmatools)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting protobuf==5.29.2 (from dadmatools)
  Using cached protobuf-5.29.2-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (2.32.3)
Requirement already satisfied: tqdm==4.67.1 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (4.67.1)
Collecting langid==1.1.6 (from dadmatools)
  Using cached langid-1.1.6.tar.gz (1.9 MB)
  Preparing metadata (setup.py) ... done
Collecting filelock==3.16.1 (from dadmatools)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting tokenizers==0.21.0 (from dadmatools)
  Using cached tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: regex==2024.11.6 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (2024.11.6)
Requirement already satisfied: packaging==24.2 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (24.2)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (0.2.0)
Collecting sacremoses==0.1.1 (from dadmatools)
  Using cached sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Collecting emoji==2.10.0 (from dadmatools)
  Using cached emoji-2.10.0-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting pandas==2.2.3 (from dadmatools)
  Using cached pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
INFO: pip is looking at multiple versions of dadmatools to determine which version is compatible with other requirements. This could take a while.
Collecting dadmatools
  Using cached dadmatools-2.1.7-py3-none-any.whl.metadata (22 kB)
  Using cached dadmatools-2.1.5-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: folium>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (0.19.5)
Requirement already satisfied: h5py>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (3.13.0)
Collecting html2text (from dadmatools)
  Using cached html2text-2025.4.15-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (1.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from dadmatools) (1.24.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from dadmatools) (5.29.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from dadmatools) (3.18.0)
Requirement already satisfied: tokenizers>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (0.21.1)
Requirement already satisfied: fasttext-wheel in /usr/local/lib/python3.11/dist-packages (from dadmatools) (0.9.2)
Collecting kenlm (from dadmatools)
  Using cached kenlm-0.3.0.tar.gz (427 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from dadmatools) (2.2.2)
Requirement already satisfied: torch>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (2.6.0+cu124)
Requirement already satisfied: transformers>=4.9.1 in /usr/local/lib/python3.11/dist-packages (from dadmatools) (4.51.3)
Collecting pytorch-transformers>=1.1.0 (from dadmatools)
  Using cached pytorch_transformers-1.2.0-py3-none-any.whl.metadata (21 kB)
Collecting tf-estimator-nightly==2.8.0.dev2021122109 (from dadmatools)
  Using cached tf_estimator_nightly-2.8.0.dev2021122109-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting supar==1.1.2 (from dadmatools)
  Using cached supar-1.1.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from Deprecated==1.2.6->dadmatools) (1.17.2)
Collecting stanza (from supar==1.1.2->dadmatools)
  Using cached stanza-1.10.1-py3-none-any.whl.metadata (13 kB)
Collecting dill (from supar==1.1.2->dadmatools)
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from folium>=0.2.1->dadmatools) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from folium>=0.2.1->dadmatools) (3.1.6)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.11/dist-packages (from folium>=0.2.1->dadmatools) (2025.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown==5.2.0->dadmatools) (4.13.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.3->dadmatools) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.3->dadmatools) (7.1.0)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from hyperopt==0.2.7->dadmatools) (1.17.0)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.11/dist-packages (from hyperopt==0.2.7->dadmatools) (3.4.2)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from hyperopt==0.2.7->dadmatools) (1.0.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from hyperopt==0.2.7->dadmatools) (3.1.1)
Requirement already satisfied: py4j in /usr/local/lib/python3.11/dist-packages (from hyperopt==0.2.7->dadmatools) (0.10.9.7)
Collecting texttable (from py7zr==0.22.0->dadmatools)
  Using cached texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting pycryptodomex>=3.16.0 (from py7zr==0.22.0->dadmatools)
  Using cached pycryptodomex-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pyzstd>=0.15.9 (from py7zr==0.22.0->dadmatools)
  Using cached pyzstd-0.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)
Collecting pyppmd<1.2.0,>=1.1.0 (from py7zr==0.22.0->dadmatools)
  Using cached pyppmd-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting pybcj<1.1.0,>=1.0.0 (from py7zr==0.22.0->dadmatools)
  Using cached pybcj-1.0.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting multivolumefile>=0.2.3 (from py7zr==0.22.0->dadmatools)
  Using cached multivolumefile-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting inflate64<1.1.0,>=1.0.0 (from py7zr==0.22.0->dadmatools)
  Using cached inflate64-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting brotli>=1.1.0 (from py7zr==0.22.0->dadmatools)
  Using cached Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->dadmatools) (5.9.5)
Collecting boto3 (from pytorch-transformers>=1.1.0->dadmatools)
  Using cached boto3-1.38.5-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->dadmatools) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->dadmatools) (3.6.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.11/dist-packages (from tokenizers>=0.7.0->dadmatools) (0.30.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (4.13.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=2.3.1->dadmatools)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.3.1->dadmatools) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.3.1->dadmatools) (1.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.9.1->dadmatools) (6.0.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.9.1->dadmatools) (0.5.3)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.11/dist-packages (from fasttext-wheel->dadmatools) (2.13.6)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from fasttext-wheel->dadmatools) (75.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk==3.9.1->dadmatools) (8.1.8)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->dadmatools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->dadmatools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->dadmatools) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->dadmatools) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->dadmatools) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->dadmatools) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->dadmatools) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.9->folium>=0.2.1->dadmatools) (3.0.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown==5.2.0->dadmatools) (2.7)
Collecting botocore<1.39.0,>=1.38.5 (from boto3->pytorch-transformers>=1.1.0->dadmatools)
  Using cached botocore-1.38.5-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->pytorch-transformers>=1.1.0->dadmatools)
  Using cached jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.13.0,>=0.12.0 (from boto3->pytorch-transformers>=1.1.0->dadmatools)
  Using cached s3transfer-0.12.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown==5.2.0->dadmatools) (1.7.1)
Using cached dadmatools-2.1.5-py3-none-any.whl (891 kB)
Using cached Deprecated-1.2.6-py2.py3-none-any.whl (8.1 kB)
Using cached emoji-2.10.0-py2.py3-none-any.whl (457 kB)
Using cached supar-1.1.2-py3-none-any.whl (87 kB)
Using cached tf_estimator_nightly-2.8.0.dev2021122109-py2.py3-none-any.whl (462 kB)
Using cached bpemb-0.3.6-py3-none-any.whl (20 kB)
Using cached py7zr-0.22.0-py3-none-any.whl (67 kB)
Using cached pyconll-3.2.0-py3-none-any.whl (27 kB)
Using cached pytorch_transformers-1.2.0-py3-none-any.whl (176 kB)
Using cached segtok-1.5.11-py3-none-any.whl (24 kB)
Using cached nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
Using cached nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
Using cached nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.5 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 76.9 MB/s eta 0:00:00
Downloading conllu-6.0.0-py3-none-any.whl (16 kB)
Downloading html2text-2025.4.15-py3-none-any.whl (34 kB)
Downloading sacremoses-0.1.1-py3-none-any.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 46.7 MB/s eta 0:00:00
Downloading Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 92.8 MB/s eta 0:00:00
Downloading inflate64-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 8.2 MB/s eta 0:00:00
Downloading multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Downloading pybcj-1.0.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 kB 3.8 MB/s eta 0:00:00
Downloading pycryptodomex-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 76.7 MB/s eta 0:00:00

In [32]:
import os
import json
import tqdm
import tqdm.notebook
import nltk
import random
import requests

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dadmatools.normalizer import Normalizer as Nm

from hazm import *
from wordcloud import WordCloud
from collections import Counter
from __future__ import unicode_literals

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [4]:
%cd ./drive/MyDrive/Provinces/
%pwd
%ls

/content/drive/MyDrive/Provinces
Hamedan/  Ilam/  Kermanshah/  Khoozestan/  Lorestan/  Markazi/

# Inititial Statistc Analysis

In [5]:
provinces = ['Hamedan/', 'Ilam/', 'Kermanshah/', 'Khoozestan/', 'Lorestan/', 'Markazi/']

In [27]:
# Number of foods for each province and Types of meal

for province in provinces:
  province_recipes_file = os.listdir("./" + province + "Modified/")
  # print(province_recipes_file)
  meal_type_list = []
  occasion_list = []
  with open("./" + province + "Modified/" + province_recipes_file[0], "r", encoding = "utf-8") as f:
      data = json.load(f)
      print(f"{province[0:len(province)-1]}:\n\n")
      print(f"Number of recipes: {len(data)}\n")
      for item in data:
          meal_type_list.extend(item.get('meal_type', []))  # meal_type is a list
          occasion_list.append(item.get('occasion'))

      count = 0
      for occasion in occasion_list:
          # print(type(occasion))
          if isinstance(occasion, list):
              # print(occasion)
              occasion_list[count] = occasion[0]
          count += 1

      # print(meal_type_list)
      # print(occasion_list)

      meal_type_counts = Counter(meal_type_list)
      occasion_counts = Counter(occasion_list)

      meal_type_df = pd.DataFrame(meal_type_counts.items(), columns=["Type", "amount"])
      left_aligned_meal_type_df = meal_type_df.style.set_properties(**{'text-align': 'left'})
      print("Types of meal:")
      display(left_aligned_meal_type_df)
      print("\n")

      occasions_df = pd.DataFrame(occasion_counts.items(), columns=["Occasion", "amount"])
      left_aligned_occasions_df = occasions_df.style.set_properties(**{'text-align': 'left'})
      print("Occasions:")
      display(left_aligned_occasions_df)
      print("\n")

Hamedan:


Number of recipes: 31

Types of meal:

Occasions:

Ilam:


Number of recipes: 25

Types of meal:

Occasions:

Kermanshah:


Number of recipes: 33

Types of meal:

Occasions:

Khoozestan:


Number of recipes: 44

Types of meal:

Occasions:

Lorestan:


Number of recipes: 30

Types of meal:

Occasions:

Markazi:


Number of recipes: 36

Types of meal:

Occasions:

# Some Random Data for result indication (Necessary to run)

In [28]:
random_provinces_indices = random.sample(range(0,len(provinces)),5)
original_recipes = []
normalized_recipes = []

# Normalization

In [29]:
def normalize_text(text):
    api_url = "https://api.pars.io/v1/nlp/normalize"
    headers = {"Content-Type": "application/json"}
    payload = {"text": text}

    try:
        response = requests.post(api_url, json = payload, headers = headers)
        if response.status_code == 200:
            return response.json().get("result", text)
        else:
            return text
    except:
        return text

# Using an API

In [10]:
for province in provinces:
  province_recipes_file = os.listdir("./" + province + "Modified/")
  # print(province_recipes_file)
  with open("./" + province + "Modified/" + province_recipes_file[0], "r", encoding = "utf-8") as f:
      original_data = json.load(f)
      normalized_text = normalize_text(original_data)
      # print(normalized_text[0])
      normalization_file_name = province[0:len(province)-1] + "_normalized.json"
      normalized_file_path = "./" + province + "Modified/" + normalization_file_name
      with open(normalized_file_path, 'w', encoding = 'utf-8') as f2:
          json.dump(normalized_text, f2, ensure_ascii = False, indent = 4)
          f2.close()
      print(province[0:len(province)-1] + " Normalized file created successfully!")
      f.close()

Hamedan Normalized file created successfully!
Ilam Normalized file created successfully!
Kermanshah Normalized file created successfully!
Khoozestan Normalized file created successfully!
Lorestan Normalized file created successfully!
Markazi Normalized file created successfully!

# Using DadmaTools

In [51]:
dadma_normalizer = Nm(
    full_cleaning=False,
    unify_chars=True,
    refine_punc_spacing=True,
    remove_extra_space=True,
    remove_puncs=False,
    remove_html=False,
    remove_stop_word=False,
    replace_email_with="<EMAIL>",
    replace_number_with=None,
    replace_url_with="",
    replace_mobile_number_with=None,
    replace_emoji_with=None,
    replace_home_number_with=None
)


for province in provinces:
  normalized_text = []
  province_recipes_file = os.listdir("./" + province + "Modified/")
  # print(province_recipes_file)
  with open("./" + province + "Modified/" + province_recipes_file[0], "r", encoding = "utf-8") as f:
      original_data = json.load(f)
      for recipe_json in tqdm.notebook.tqdm(original_data):
          for item in recipe_json.items():
              if item[0] == 'instructions':
                  normalized_text.append(dadma_normalizer.normalize(item[1][0]))
      normalization_file_name = province[0:len(province)-1] + "_normalized_with_DadmaTools.json"
      normalized_file_path = "./" + province + "Modified/" + normalization_file_name
      with open(normalized_file_path, 'w', encoding = 'utf-8') as f2:
          json.dump(normalized_text, f2, ensure_ascii = False, indent = 4)
          f2.close()
      print(province[0:len(province)-1] + " Normalized file using dadmatools created successfully!")
      f.close()

  0%|          | 0/31 [00:00<?, ?it/s]

Hamedan Normalized file using dadmatools created successfully!

  0%|          | 0/25 [00:00<?, ?it/s]

Ilam Normalized file using dadmatools created successfully!

  0%|          | 0/33 [00:00<?, ?it/s]

Kermanshah Normalized file using dadmatools created successfully!

  0%|          | 0/44 [00:00<?, ?it/s]

Khoozestan Normalized file using dadmatools created successfully!

  0%|          | 0/30 [00:00<?, ?it/s]

Lorestan Normalized file using dadmatools created successfully!

  0%|          | 0/36 [00:00<?, ?it/s]

Markazi Normalized file using dadmatools created successfully!

# Example Output for Normalization with DadmaTools

In [91]:
original_recipes = []
normalized_recipes = []
for province_index in random_provinces_indices:
  province_recipes_file = os.listdir("./" + provinces[province_index] + "Modified/")
  with open("./" + provinces[province_index] + "Modified/" + province_recipes_file[0], "r", encoding = "utf-8") as f:
      original_data = json.load(f)
      random_recipe_index = random.sample(range(0,len(original_data)), 1)
      original_recipes.append(original_data[random_recipe_index[0]]['instructions'][0])
      normalized_file_name = provinces[province_index][0:len(provinces[province_index])-1] + "_normalized_with_DadmaTools.json"
      normalized_file_path = "./" + provinces[province_index] + "Modified/" + normalized_file_name
      with open(normalized_file_path, 'r', encoding = 'utf-8') as f2:
          normalized_data = json.load(f2)
          normalized_recipes.append(normalized_data[random_recipe_index[0]])
          f2.close()
      f.close()


instructions_df = pd.DataFrame({'original_text':[original_recipes[idx] for idx in range(len(original_recipes))],
                   'dadma_normalized':[normalized_recipes[idx] for idx in range(len(normalized_recipes))]
                  })

left_aligned_instructions_df = instructions_df.style.set_properties(**{'text-align': 'left'})
print("Instance Instructions:")
display(left_aligned_instructions_df)
print("\n")

Instance Instructions:

# Example Output for Normalization and Sentence Tokenization with Hazm

In [93]:
hazm_normalizer = Normalizer()
recipes_normalized_hazm = [hazm_normalizer.normalize(x) for x in tqdm.notebook.tqdm(original_recipes)]
recipes_sentences = [sent_tokenize(x) for x in tqdm.notebook.tqdm(recipes_normalized_hazm)]
instructions_df_Hazm = pd.DataFrame({'original_text':[original_recipes[idx] for idx in range(len(original_recipes))],
                   'hazm_text':['---'.join(recipes_sentences[idx]) for idx in range(len(recipes_sentences))]
                  })

left_aligned_instructions_df_Hazm = instructions_df_Hazm.style.set_properties(**{'text-align': 'left'})
print("Instance Instructions:")
display(left_aligned_instructions_df_Hazm)
print("\n")

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

Instance Instructions:

# Normalization, Sentence Tokenization and Word Tokenization using Hazm (The most complete one)

In [110]:
# hazm_normalizer = Normalizer()
__recipes_sentences = []
__recipe_words = []

for province in provinces:
  normalized_text = []
  province_recipes_file = os.listdir("./" + province + "Modified/")
  # print(province_recipes_file)
  with open("./" + province + "Modified/" + province_recipes_file[0], "r", encoding = "utf-8") as f:
      original_data = json.load(f)
      # print(len(original_data))

      for recipe_json in tqdm.notebook.tqdm(original_data):
          for item in recipe_json.items():
              if item[0] == 'instructions':
                  normalized_text.append(dadma_normalizer.normalize(item[1][0]))

      recipes_sentences = [sent_tokenize(x) for x in tqdm.notebook.tqdm(normalized_text)]
      __recipes_sentences += recipes_sentences
      recipe_tokens = [[word_tokenize(sent) for sent in sents] for sents in tqdm.notebook.tqdm(recipes_sentences)]
      __recipe_words += recipe_tokens
      # print(normalized_text[0])
      normalization_file_name = province[0:len(province)-1] + "_normalized_with_Hazm.json"
      sentence_tokenization_file_name = province[0:len(province)-1] + "_normalized_and_tokenized_with_Hazm.json"
      word_tokenization_file_name = province[0:len(province)-1] + "_normalized_and_sentence_and_word_tokenized_with_Hazm.json"
      normalized_file_path = "./" + province + "Modified/" + normalization_file_name
      sentence_tokenization_file_path = "./" + province + "Modified/" + sentence_tokenization_file_name
      word_tokenization_file_path = "./" + province + "Modified/" + word_tokenization_file_name
      with open(normalized_file_path, 'w', encoding = 'utf-8') as f2:
          json.dump(normalized_recipes, f2, ensure_ascii = False, indent = 4)
          f2.close()
      with open(sentence_tokenization_file_path, 'w', encoding = 'utf-8') as f3:
          json.dump(recipes_sentences, f3, ensure_ascii = False, indent = 4)
          f3.close()
      with open(word_tokenization_file_path, 'w', encoding = 'utf-8') as f4:
          json.dump(recipe_tokens, f4, ensure_ascii = False, indent = 4)
          f4.close()
      print(province[0:len(province)-1] + " Normalized and Sentence Tokenized and Word Tokenized files created successfully!")
      f.close()

  0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/31 [00:00<?, ?it/s]

Hamedan Normalized and Sentence Tokenized and Word Tokenized files created successfully!

  0%|          | 0/25 [00:00<?, ?it/s]

  0%|          | 0/25 [00:00<?, ?it/s]

  0%|          | 0/25 [00:00<?, ?it/s]

Ilam Normalized and Sentence Tokenized and Word Tokenized files created successfully!

  0%|          | 0/33 [00:00<?, ?it/s]

  0%|          | 0/33 [00:00<?, ?it/s]

  0%|          | 0/33 [00:00<?, ?it/s]

Kermanshah Normalized and Sentence Tokenized and Word Tokenized files created successfully!

  0%|          | 0/44 [00:00<?, ?it/s]

  0%|          | 0/44 [00:00<?, ?it/s]

  0%|          | 0/44 [00:00<?, ?it/s]

Khoozestan Normalized and Sentence Tokenized and Word Tokenized files created successfully!

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

Lorestan Normalized and Sentence Tokenized and Word Tokenized files created successfully!

  0%|          | 0/36 [00:00<?, ?it/s]

  0%|          | 0/36 [00:00<?, ?it/s]

  0%|          | 0/36 [00:00<?, ?it/s]

Markazi Normalized and Sentence Tokenized and Word Tokenized files created successfully!

# Example Output for Word Tokenization with Hazm

In [111]:
instructions_df_Hazm = pd.DataFrame({
                   'Hazm_recipe_sentences':[__recipes_sentences[idx] for idx in range(len(__recipes_sentences))],
                    'Hazm_recipe_words':[__recipe_words[idx] for idx in range(len(__recipe_words))]
                  })

left_aligned_instructions_df_Hazm = instructions_df_Hazm.style.set_properties(**{'text-align': 'left'})
print("Instance Instructions using Hazm:")
display(left_aligned_instructions_df_Hazm)
print("\n")

Instance Instructions using Hazm:

# Frequency Analysis for All Province Data

In [113]:
# nltk.download()
from nltk import FreqDist
import itertools

In [116]:
province_tokens = []
dataframe = {}
province_index = 0
for province in provinces:
  province_recipes_file = os.listdir("./" + province + "Modified/")
  word_tokenization_file_name = province[0:len(province)-1] + "_normalized_and_sentence_and_word_tokenized_with_Hazm.json"
  word_tokenization_file_path = "./" + province + "Modified/" + word_tokenization_file_name
  with open(word_tokenization_file_path, 'r', encoding = 'utf-8') as f:
      word_tokenized_data = json.load(f)
      province_tokens.append(itertools.chain(*itertools.chain(*word_tokenized_data)))
      # dataframe[province] = FreqDist(eval(F"province_tokens")).most_common(25)
      dataframe[province] = FreqDist(province_tokens[province_index]).most_common(25)
      province_index += 1
      f.close()

freq_analysis = pd.DataFrame(dataframe)
left_aligned_freq_analysis = freq_analysis.style.set_properties(**{'text-align': 'left'})
print("Word Frequency Analysis using Hazm:")
display(freq_analysis)
print("\n")

Word Frequency Analysis using Hazm:

,Hamedan/,Ilam/,Kermanshah/,Khoozestan/,Lorestan/,Markazi/
0,"(و, 100)","(و, 61)","(و, 95)","(و, 95)","(و, 67)","(و, 105)"
1,"(رو, 35)","(., 46)","(را, 55)","(را, 40)","(را, 32)","(را, 47)"
2,"(را, 30)","(از, 25)","(., 38)","(., 39)","(., 28)","(., 35)"
3,"(., 27)","(،, 22)","(تا, 26)","(آب, 26)","(،, 27)","(رو, 31)"
4,"(اضافه, 26)","(به, 21)","(رو, 23)","(رو, 25)","(تا, 16)","(آب, 24)"
5,"(کنید, 25)","(را, 21)","(با, 22)","(،, 25)","(اضافه, 16)","(با, 23)"
6,"(،, 25)","(این, 18)","(از, 22)","(با, 24)","(کرده, 15)","(به, 21)"
7,"(با, 21)","(در, 15)","(کنید, 19)","(تا, 23)","(رو, 14)","(اضافه, 21)"
8,"(بعد, 21)","(با, 12)","(کرده, 17)","(به, 18)","(آب, 14)","(کنید, 19)"
9,"(تا, 21)","(که, 11)","(اضافه, 16)","(از, 17)","(با, 12)","(بعد, 17)"
10,"(به, 20)","(کنید, 11)","(میکنیم, 15)","(کنید, 17)","(که, 12)","(پیاز, 16)"
11,"(کردم, 16)","(رو, 10)","(هم, 14)","(بعد, 17)","(گندم, 12)","(،, 16)"
12,"(هم, 15)","(است, 10)","(به, 13)","(اضافه, 17)","(به, 11)","(کرده, 16)"
13,"(از, 14)","(برای, 9)","(پیاز, 13)","(در, 16)","(یک, 11)","(از, 15)"
14,"(کرده, 13)","(غذاهای, 8)","(بعد, 13)","(میکنیم, 16)","(از, 11)","(میکنیم, 14)"
15,"(پیاز, 12)","(تا, 8)","(در, 12)","(کرده, 14)","(بعد, 11)","(تا, 14)"
16,"(میکنیم, 12)","(آب, 8)","(گوشت, 11)","(خیس, 12)","(نمک, 10)","(گوشت, 13)"
17,"(گوشت, 11)","(غذا, 8)","(آب, 11)","(ها, 12)","(مخلوط, 10)","(هم, 13)"
18,"(آب, 11)","(ایلام, 8)","(،, 11)","(که, 12)","(کردم, 8)","(که, 12)"
19,"(آرد, 11)","(شده, 7)","(خیس, 10)","(هم, 12)","(روی, 7)","(در, 11)"
20,"(کم, 11)","(آن, 7)","(نمک, 10)","(پیاز, 11)","(بشه, 7)","(روغن, 10)"
21,"(یا, 9)","(آش, 6)","(برنج, 10)","(برنج, 10)","(خوب, 7)","(مخلوط, 10)"
22,"(خیس, 9)","(یکی, 6)","(قبل, 9)","(گوشت, 10)","(در, 7)","(قابلمه, 9)"
23,"(نمک, 9)","(دارد, 6)","(روی, 9)","(ابتدا, 10)","(داخل, 7)","(خیس, 9)"
24,"(کمی, 9)","(یک, 6)","(شود, 9)","(می, 9)","(شیر, 7)","(نمک, 9)"

No charts were generated by quickchart

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_2['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

In [123]:
# l = len(list(province_tokens))
# for province_index in range(len(provinces)):
#   print(provinces[province_index][0:len(provinces[province_index])-1] + ":\n\n")
#   print ('%-16s' % 'Number of words', '%-16s' % l)
#   print ('%-16s' % 'Number of unique words', '%-16s' % len(set(province_tokens[province_index])))
#   avg=np.sum([len(word) for word in province_tokens[province_index]])/l
#   print ('%-16s' % 'Average word length', '%-16s' % avg)
#   print ('%-16s' % 'Longest word', '%-16s' % province_tokens[province_index][np.argmax([len(word) for word in province_tokens[province_index]])])

Hamedan:


Number of words  6
Number of unique words 0
Average word length 0.0

ValueError: attempt to get argmax of an empty sequence